version: '3.9'

networks:
  triphippie:
    driver: bridge

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - triphippie
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      IMAGE_PATH: /app/resources
    depends_on:
      - db
    networks:
      - triphippie
    ports:
      - "8765:8765"
    volumes:
      - ./resources:/app/resources

volumes:
  db:
    driver: local


